#! /bin/sh

prefix=${NEST_INSTALL_DIR:-/home/christoph/nest-simulator-2.14.0}
exec_prefix=${prefix}

usage()
{
    cat <<EOF
Usage: nest-config [OPTION]

Known values for OPTION are:

  --prefix              NEST install prefix for architecture-independent files
  --exec-prefix         NEST install prefix for architecture-dependent files
  --libs                print library linking information
  --cflags              print pre-processor and compiler flags
  --includes            print includes
  --compiler            print the compiler used to compile NEST
  --static-libraries    print "ON" if configured for static libraries, "OFF" otherwise
  --docdir              print the relative path (to prefix) to the installed documentation
  --datadir             print the relative path (to prefix) to the installed data
  --libdir              print the relative path (to prefix) to the installed libraries
  --help                display this help and exit
  --version             output version information

EOF

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

cflags=false
libs=false

while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
    esac

    case "$1" in
    --prefix=*)
        prefix=$optarg
        ;;
    --prefix)
        echo $prefix
        ;;
    --exec-prefix)
        echo $exec_prefix
        ;;
    --version)
        echo "2.14.0"
        ;;
    --help)
        usage 0
        ;;
    --includes)
        echo " -I/home/christoph/nest-simulator-2.14.0-src/libnestutil -I/home/christoph/Documents/bachelor-thesis/Locomotion_of_snake_via_SNN/libnestutil -I/home/christoph/nest-simulator-2.14.0-src/librandom -I/home/christoph/nest-simulator-2.14.0-src/sli -I/home/christoph/nest-simulator-2.14.0-src/topology -I/home/christoph/nest-simulator-2.14.0-src/nestkernel -I/home/christoph/nest-simulator-2.14.0-src/nest -I/usr/include"
        ;;
    --cflags)
        echo " -O2 -Wall -fopenmp -fdiagnostics-color=auto"
        ;;
    --libs)
        echo "-L$prefix/lib -lnestutil -lnest -lrandom -lsli -lnestkernel -fopenmp /usr/lib/x86_64-linux-gnu/libltdl.so     "
        ;;
    --compiler)
        echo "/usr/bin/c++"
        ;;

    --static-libraries)
        echo "OFF"
        ;;
    --docdir)
        echo "share/doc/nest"
        ;;
    --datadir)
        echo "share/nest"
        ;;
    --libdir)
        echo "lib"
        ;;
    *)
        usage
        exit 1
        ;;
    esac
    shift
done

exit 0
